# Generated by Django 3.2 on 2022-08-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('url', models.URLField(unique=True, verbose_name='آدرس سایت')),
            ],
            options={
                'verbose_name': 'سایت خارجی',
                'verbose_name_plural': 'سایت های خارجی',
            },
        ),
        migrations.CreateModel(
            name='PersianSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('url', models.URLField(unique=True, verbose_name='آدرس سایت')),
            ],
            options={
                'verbose_name': 'سایت ایرانی',
                'verbose_name_plural': 'سایت های ایرانی',
            },
        ),
    ]
